import RouterComponents from "./components/routes/RouterComponents";
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap/dist/js/bootstrap.bundle.min.js"
import "./assets/css/style.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import "font-awesome/css/font-awesome.css"
import "font-awesome/css/font-awesome.min.css"
import "font-awesome/fonts/fontawesome-webfont.svg"
import "font-awesome-icons/data/icons.json"


// import "./assets/scss/bootstrap.scss"


// import "./assets/scss/bootstrap/scss/_accordion.scss"
// import "bootstrap/scss/_accordion.scss"
// import "./assets/scss/bootstrap/scss/_alert.scss"
// import "./assets/scss/bootstrap/scss/_badge.scss"
// import "./assets/scss/bootstrap/scss/_breadcrumb.scss"
// import "./assets/scss/bootstrap/scss/_button-group.scss"
// import "./assets/scss/bootstrap/scss/_buttons.scss"
// import "./assets/scss/bootstrap/scss/_card.scss"
// import "./assets/scss/bootstrap/scss/_carousel.scss"
// import "./assets/scss/bootstrap/scss/_close.scss"
// import "./assets/scss/bootstrap/scss/_containers.scss"
// import "./assets/scss/bootstrap/scss/_dropdown.scss"
// import "./assets/scss/bootstrap/scss/_forms.scss"
// import "./assets/scss/bootstrap/scss/_functions.scss"
// import "./assets/scss/bootstrap/scss/_grid.scss"
// import "./assets/scss/bootstrap/scss/_helpers.scss"
// import "./assets/scss/bootstrap/scss/_images.scss"
// import "./assets/scss/bootstrap/scss/_list-group.scss"
// import "./assets/scss/bootstrap/scss/_mixins.scss"
// import "./assets/scss/bootstrap/scss/_modal.scss"
// import "./assets/scss/bootstrap/scss/_nav.scss"
// import "./assets/scss/bootstrap/scss/_navbar.scss"
// import "./assets/scss/bootstrap/scss/_offcanvas.scss"
// import "./assets/scss/bootstrap/scss/_pagination.scss"
// import "./assets/scss/bootstrap/scss/_popover.scss"
// import "./assets/scss/bootstrap/scss/_progress.scss"
// import "./assets/scss/bootstrap/scss/_reboot.scss"
// import "./assets/scss/bootstrap/scss/_root.scss"
// import "./assets/scss/bootstrap/scss/_spinners.scss"
// import "./assets/scss/bootstrap/scss/_tables.scss"
// import "./assets/scss/bootstrap/scss/_toasts.scss"
// import "./assets/scss/bootstrap/scss/_tooltip.scss"
// import "./assets/scss/bootstrap/scss/_transitions.scss"
// import "./assets/scss/bootstrap/scss/_type.scss"
// import "./assets/scss/bootstrap/scss/_utilities.scss"
// import "./assets/scss/bootstrap/scss/_variables.scss"
// import "./assets/scss/bootstrap/scss/bootstrap-grid.scss"
// import "./assets/scss/bootstrap/scss/bootstrap-reboot.scss"
// import "./assets/scss/bootstrap/scss/bootstrap-utilities.scss"
// import "./assets/scss/bootstrap/scss/bootstrap.scss"
// import "./assets/scss/bootstrap/scss/forms/_floating-labels.scss"
// import "./assets/scss/bootstrap/scss/forms/_form-check.scss"
// import "./assets/scss/bootstrap/scss/forms/_form-control.scss"
// import "./assets/scss/bootstrap/scss/forms/_form-range.scss"
// import "./assets/scss/bootstrap/scss/forms/_form-select.scss"
// import "./assets/scss/bootstrap/scss/forms/_form-text.scss"
// import "./assets/scss/bootstrap/scss/forms/_input-group.scss"
// import "./assets/scss/bootstrap/scss/forms/_labels.scss"
// import "./assets/scss/bootstrap/scss/forms/_validation.scss"
// import "./assets/scss/bootstrap/scss/helpers/_clearfix.scss"
// import "./assets/scss/bootstrap/scss/helpers/_colored-links.scss"
// import "./assets/scss/bootstrap/scss/helpers/_ratio.scss"
// import "./assets/scss/bootstrap/scss/helpers/_stretched-link.scss"
// import "./assets/scss/bootstrap/scss/helpers/_text-truncation.scss"
// import "./assets/scss/bootstrap/scss/helpers/_visually-hidden.scss"
// import "./assets/scss/bootstrap/scss/mixins/_alert.scss"
// import "./assets/scss/bootstrap/scss/mixins/_border-radius.scss"
// import "./assets/scss/bootstrap/scss/mixins/_box-shadow.scss"
// import "./assets/scss/bootstrap/scss/mixins/_breakpoints.scss"
// import "./assets/scss/bootstrap/scss/mixins/_buttons.scss"
// import "./assets/scss/bootstrap/scss/mixins/_caret.scss"
// import "./assets/scss/bootstrap/scss/mixins/_clearfix.scss"
// import "./assets/scss/bootstrap/scss/mixins/_color-scheme.scss"
// import "./assets/scss/bootstrap/scss/mixins/_container.scss"
// import "./assets/scss/bootstrap/scss/mixins/_deprecate.scss"
// import "./assets/scss/bootstrap/scss/mixins/_forms.scss"
// import "./assets/scss/bootstrap/scss/mixins/_gradients.scss"
// import "./assets/scss/bootstrap/scss/mixins/_grid.scss"
// import "./assets/scss/bootstrap/scss/mixins/_grid.scss"
// import "./assets/scss/bootstrap/scss/mixins/_image.scss"
// import "./assets/scss/bootstrap/scss/mixins/_list-group.scss"
// import "./assets/scss/bootstrap/scss/mixins/_lists.scss"
// import "./assets/scss/bootstrap/scss/mixins/_pagination.scss"
// import "./assets/scss/bootstrap/scss/mixins/_reset-text.scss"
// import "./assets/scss/bootstrap/scss/mixins/_resize.scss"
// import "./assets/scss/bootstrap/scss/mixins/_table-variants.scss"
// import "./assets/scss/bootstrap/scss/mixins/_text-truncate.scss"
// import "./assets/scss/bootstrap/scss/mixins/_transition.scss"
// import "./assets/scss/bootstrap/scss/mixins/_utilities.scss"
// import "./assets/scss/bootstrap/scss/mixins/_visually-hidden.scss"
// import "./assets/scss/bootstrap/scss/utilities/_api.scss"
// import "./assets/scss/bootstrap/scss/vendor/_rfs.scss"
// import HeaderComponents from "./components/layouts/HeaderComponents";

function App() {
  return (
    <>
      <RouterComponents/>
    </>
  )
}

export default App
